/**
 * MVP 시드 사료 데이터셋 (수입 전용, 예시 큐레이션).
 *
 * ⚠ 영양값은 라벨 as-fed 기준. 인(P)%는 per_1000kcal 환산이 임상 목표에 들어맞도록
 * 역산해 넣었다(예: 신장식 wet P 0.10% × 1000 / 88 kcal ≈ 1.1 g/1000kcal).
 * dev-plan §M0.5 실제 시드(GH #10)로 교체 전까지의 엔진 구동용 데이터.
 *
 * tags: 엔진 검출용 플래그(rules.KEYWORDS와 매칭). 모두 staple_complete.
 * ingredient_keywords: 알레르겐/원료 검출용(한국어 토큰).
 */
import type { Food } from '@/lib/domain/types';
import { AGE_GROUPS } from '@/lib/domain/constants';

const ALL_AGES = [...AGE_GROUPS];

function food(f: Partial<Food> & Pick<Food, 'id' | 'brand' | 'product_name' | 'category'>): Food {
  return {
    age_fit: ALL_AGES,
    condition_fit: [],
    protein_pct: null,
    fat_pct: null,
    fiber_pct: null,
    ash_pct: null,
    moisture_pct: null,
    phosphorus_pct: null,
    sodium_pct: null,
    omega3_pct: null,
    kcal_per_100g: null,
    ingredient_summary: null,
    ingredient_keywords: [],
    form: null,
    rec_daily_g: null,
    tags: ['staple_complete'],
    image_url: null,
    affiliate_links: null,
    price_per_kg_krw: null,
    active: true,
    ...f,
  };
}

export const SEED_FOODS: Food[] = [
  // ── 신장(CKD) 저인 ──
  food({
    id: 'renal-wet-01',
    brand: 'KidneyCare',
    product_name: '리날 서포트 습식',
    category: '습식',
    condition_fit: ['ckd'],
    protein_pct: 9,
    fat_pct: 6,
    fiber_pct: 1,
    ash_pct: 1.5,
    moisture_pct: 78,
    phosphorus_pct: 0.1,
    sodium_pct: 0.08,
    omega3_pct: 0.4,
    kcal_per_100g: 90,
    ingredient_summary: '달걀·쌀 기반 저인 신장 처방 습식',
    ingredient_keywords: ['달걀', '쌀'],
    form: '파우치',
    rec_daily_g: 220,
    tags: ['staple_complete', 'renal', 'low_phosphorus'],
    price_per_kg_krw: 18000,
  }),
  food({
    id: 'renal-dry-02',
    brand: 'KidneyCare',
    product_name: '리날 서포트 건식',
    category: '건식',
    condition_fit: ['ckd'],
    protein_pct: 28,
    fat_pct: 16,
    fiber_pct: 3,
    ash_pct: 5,
    moisture_pct: 8,
    phosphorus_pct: 0.43,
    sodium_pct: 0.2,
    omega3_pct: 0.5,
    kcal_per_100g: 390,
    ingredient_summary: '달걀 단백 중심 저인 신장 건식',
    ingredient_keywords: ['달걀', '쌀'],
    form: '건식',
    rec_daily_g: 55,
    tags: ['staple_complete', 'renal', 'low_phosphorus'],
    price_per_kg_krw: 16000,
  }),

  // ── 요로 ──
  food({
    id: 'urinary-struvite-01',
    brand: 'UroBalance',
    product_name: '유리너리 SO 습식',
    category: '습식',
    condition_fit: ['struvite'],
    protein_pct: 11,
    fat_pct: 5,
    fiber_pct: 1,
    ash_pct: 2,
    moisture_pct: 79,
    phosphorus_pct: 0.18,
    sodium_pct: 0.25,
    omega3_pct: 0.2,
    kcal_per_100g: 92,
    ingredient_summary: '스트루바이트 용해용 산성화·고수분 습식',
    ingredient_keywords: ['닭'],
    form: '캔',
    rec_daily_g: 230,
    tags: ['staple_complete', 'acidifier', 'urinary'],
    price_per_kg_krw: 17000,
  }),
  food({
    id: 'urinary-multi-02',
    brand: 'UroBalance',
    product_name: '유리너리 멀티 습식',
    category: '습식',
    condition_fit: ['oxalate', 'struvite'],
    protein_pct: 12,
    fat_pct: 6,
    fiber_pct: 1,
    ash_pct: 1.8,
    moisture_pct: 78,
    phosphorus_pct: 0.16,
    sodium_pct: 0.18,
    omega3_pct: 0.3,
    kcal_per_100g: 95,
    ingredient_summary: '옥살레이트·스트루바이트 공통 희석형 습식 (비산성화)',
    ingredient_keywords: ['칠면조'],
    form: '파우치',
    rec_daily_g: 225,
    tags: ['staple_complete', 'urinary'],
    price_per_kg_krw: 17500,
  }),

  // ── 당뇨 (저탄수·고단백 습식) ──
  food({
    id: 'diabetic-wet-01',
    brand: 'GlucoBalance',
    product_name: '다이아 컨트롤 습식',
    category: '습식',
    condition_fit: ['diabetes'],
    protein_pct: 13,
    fat_pct: 6,
    fiber_pct: 1,
    ash_pct: 2,
    moisture_pct: 78,
    phosphorus_pct: 0.2,
    sodium_pct: 0.15,
    omega3_pct: 0.3,
    kcal_per_100g: 95,
    ingredient_summary: '무가당 저탄수·고단백 혈당 관리 습식',
    ingredient_keywords: ['닭'],
    form: '캔',
    rec_daily_g: 210,
    tags: ['staple_complete', 'low_carb'],
    price_per_kg_krw: 16500,
  }),
  food({
    id: 'diabetic-wet-02',
    brand: 'PureMeat',
    product_name: '그레인프리 패티',
    category: '습식',
    condition_fit: ['diabetes'],
    protein_pct: 14,
    fat_pct: 7,
    fiber_pct: 0.5,
    ash_pct: 2,
    moisture_pct: 76,
    phosphorus_pct: 0.22,
    sodium_pct: 0.16,
    omega3_pct: 0.25,
    kcal_per_100g: 112,
    ingredient_summary: '곡물 무함유 단일 단백 고단백 패티',
    ingredient_keywords: ['칠면조'],
    form: '파우치',
    rec_daily_g: 190,
    tags: ['staple_complete', 'grain_free', 'low_carb'],
    price_per_kg_krw: 19000,
  }),

  // ── 체중 감량 ──
  food({
    id: 'weight-light-01',
    brand: 'LeanLife',
    product_name: '라이트 핏 건식',
    category: '건식',
    condition_fit: ['weight'],
    protein_pct: 40,
    fat_pct: 9,
    fiber_pct: 9,
    ash_pct: 7,
    moisture_pct: 9,
    phosphorus_pct: 1.0,
    sodium_pct: 0.3,
    omega3_pct: 0.3,
    kcal_per_100g: 305,
    ingredient_summary: '고단백·고섬유 저칼로리 체중관리 건식',
    ingredient_keywords: ['닭'],
    form: '건식',
    rec_daily_g: 50,
    tags: ['staple_complete', 'weight_control'],
    price_per_kg_krw: 14000,
  }),
  food({
    id: 'weight-light-02',
    brand: 'LeanLife',
    product_name: '포만감 습식',
    category: '습식',
    condition_fit: ['weight'],
    protein_pct: 12,
    fat_pct: 3,
    fiber_pct: 2,
    ash_pct: 2,
    moisture_pct: 80,
    phosphorus_pct: 0.18,
    sodium_pct: 0.15,
    omega3_pct: 0.2,
    kcal_per_100g: 72,
    ingredient_summary: '저지방 고수분 포만감 습식',
    ingredient_keywords: ['생선'],
    form: '파우치',
    rec_daily_g: 240,
    tags: ['staple_complete', 'weight_control'],
    price_per_kg_krw: 13000,
  }),

  // ── 체중 증량 / 고에너지 ──
  food({
    id: 'weight-gain-01',
    brand: 'VitalGain',
    product_name: '리커버리 고열량 건식',
    category: '건식',
    condition_fit: ['weight'],
    protein_pct: 36,
    fat_pct: 22,
    fiber_pct: 2,
    ash_pct: 6,
    moisture_pct: 8,
    phosphorus_pct: 1.0,
    sodium_pct: 0.3,
    omega3_pct: 0.4,
    kcal_per_100g: 445,
    ingredient_summary: '고지방·고에너지 회복·증량 건식',
    ingredient_keywords: ['닭'],
    form: '건식',
    rec_daily_g: 45,
    tags: ['staple_complete', 'energy_dense'],
    price_per_kg_krw: 18000,
  }),
  food({
    id: 'weight-gain-02',
    brand: 'VitalGain',
    product_name: '에너지 무스 습식',
    category: '습식',
    condition_fit: ['weight'],
    protein_pct: 11,
    fat_pct: 9,
    fiber_pct: 0.5,
    ash_pct: 2,
    moisture_pct: 74,
    phosphorus_pct: 0.2,
    sodium_pct: 0.15,
    omega3_pct: 0.3,
    kcal_per_100g: 135,
    ingredient_summary: '고열량 무스 타입 습식',
    ingredient_keywords: ['칠면조'],
    form: '캔',
    rec_daily_g: 170,
    tags: ['staple_complete', 'energy_dense'],
    price_per_kg_krw: 16000,
  }),

  // ── IBD / 알레르기 / 췌장염 ──
  food({
    id: 'ibd-hydro-01',
    brand: 'GutCalm',
    product_name: '하이드로 케어 건식',
    category: '건식',
    condition_fit: ['ibd', 'pancreatitis', 'allergy'],
    protein_pct: 30,
    fat_pct: 15,
    fiber_pct: 3,
    ash_pct: 6,
    moisture_pct: 8,
    phosphorus_pct: 0.9,
    sodium_pct: 0.3,
    omega3_pct: 0.6,
    kcal_per_100g: 385,
    ingredient_summary: '가수분해 단백 고소화성 장 관리 건식',
    ingredient_keywords: ['가수분해', '대두'],
    form: '건식',
    rec_daily_g: 52,
    tags: ['staple_complete', 'hydrolyzed', 'digest'],
    price_per_kg_krw: 22000,
  }),
  food({
    id: 'ibd-novel-02',
    brand: 'GutCalm',
    product_name: '노벨 베니슨 습식',
    category: '습식',
    condition_fit: ['ibd', 'allergy'],
    protein_pct: 11,
    fat_pct: 6,
    fiber_pct: 1,
    ash_pct: 2,
    moisture_pct: 77,
    phosphorus_pct: 0.2,
    sodium_pct: 0.15,
    omega3_pct: 0.4,
    kcal_per_100g: 98,
    ingredient_summary: '신규 단백(사슴) 단일 단백원 습식',
    ingredient_keywords: ['사슴', 'novel'],
    form: '파우치',
    rec_daily_g: 215,
    tags: ['staple_complete', 'novel_protein'],
    price_per_kg_krw: 21000,
  }),

  // ── 노령 (고단백·저인) ──
  food({
    id: 'senior-dry-01',
    brand: 'GoldenYears',
    product_name: '시니어 비탈리티 건식',
    category: '건식',
    condition_fit: ['senior'],
    protein_pct: 36,
    fat_pct: 16,
    fiber_pct: 3,
    ash_pct: 6,
    moisture_pct: 8,
    phosphorus_pct: 0.52,
    sodium_pct: 0.25,
    omega3_pct: 0.6,
    kcal_per_100g: 400,
    ingredient_summary: '고품질 단백·예방적 저인·오메가3 노령 건식',
    ingredient_keywords: ['닭', '달걀'],
    form: '건식',
    rec_daily_g: 50,
    tags: ['staple_complete', 'senior', 'low_phosphorus'],
    price_per_kg_krw: 17000,
  }),
  food({
    id: 'senior-wet-02',
    brand: 'GoldenYears',
    product_name: '골든 시니어 습식',
    category: '습식',
    condition_fit: ['senior'],
    protein_pct: 12,
    fat_pct: 7,
    fiber_pct: 1,
    ash_pct: 2,
    moisture_pct: 77,
    phosphorus_pct: 0.16,
    sodium_pct: 0.15,
    omega3_pct: 0.5,
    kcal_per_100g: 100,
    ingredient_summary: '기호성·수분 강화 노령 습식',
    ingredient_keywords: ['생선'],
    form: '파우치',
    rec_daily_g: 200,
    tags: ['staple_complete', 'senior'],
    price_per_kg_krw: 15000,
  }),

  // ── 일반 성묘 ──
  food({
    id: 'adult-daily-01',
    brand: 'DailyWell',
    product_name: '데일리 인도어 어덜트',
    category: '건식',
    condition_fit: [],
    protein_pct: 33,
    fat_pct: 14,
    fiber_pct: 3,
    ash_pct: 7,
    moisture_pct: 10,
    phosphorus_pct: 1.1,
    sodium_pct: 0.35,
    omega3_pct: 0.2,
    kcal_per_100g: 375,
    ingredient_summary: '실내묘 균형 성묘 유지식 건식',
    ingredient_keywords: ['닭', '쌀'],
    form: '건식',
    rec_daily_g: 55,
    tags: ['staple_complete', 'adult'],
    price_per_kg_krw: 11000,
  }),

  // ── 배제 시연용(저품질 대량유통) ──
  food({
    id: 'budget-dry-99',
    brand: 'BudgetChoice',
    product_name: '벗짓 포뮬러 건식',
    category: '건식',
    condition_fit: [],
    protein_pct: 30,
    fat_pct: 12,
    fiber_pct: 3,
    ash_pct: 8,
    moisture_pct: 10,
    phosphorus_pct: 1.4,
    sodium_pct: 0.5,
    omega3_pct: 0.1,
    kcal_per_100g: 360,
    ingredient_summary: '인산염·산성화제·당밀 함유 대량유통 건식',
    ingredient_keywords: ['닭', '옥수수', '당밀'],
    form: '건식',
    rec_daily_g: 60,
    tags: ['staple_complete', 'inorganic_phosphate', 'acidifier', 'added_sugar'],
    price_per_kg_krw: 6000,
  }),
  food({
    id: 'treat-soft-99',
    brand: 'SoftBite',
    product_name: '소프트 트릿 팩',
    category: '습식',
    condition_fit: [],
    protein_pct: 10,
    fat_pct: 4,
    fiber_pct: 1,
    ash_pct: 2,
    moisture_pct: 30,
    phosphorus_pct: 0.3,
    sodium_pct: 0.4,
    omega3_pct: 0,
    kcal_per_100g: 300,
    ingredient_summary: '프로필렌글리콜 함유 반습식 간식 (주식 아님)',
    ingredient_keywords: ['닭', '설탕'],
    form: '반습식',
    rec_daily_g: 20,
    tags: ['treat', 'semi_moist', 'propylene_glycol', 'added_sugar'],
    price_per_kg_krw: 9000,
  }),
];
